// Generate a runtime `frontend/config.js` file from environment variables.
// Usage: run during CI/build (Netlify) to write the BACKEND_URL that the frontend will use.
import fs from 'fs';
import path from 'path';

const BACKEND_URL = process.env.BACKEND_URL || process.env.FRONTEND_BACKEND_URL || '';
const outDir = path.join(process.cwd(), 'frontend');
const outFile = path.join(outDir, 'config.js');

if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

const content = `// Auto-generated by scripts/generate_frontend_config.js
// Set at build time by CI (Netlify) to point the frontend at the deployed backend.
window.BACKEND_URL = ${JSON.stringify(BACKEND_URL)};
`;

fs.writeFileSync(outFile, content, 'utf8');
console.log('Wrote', outFile, 'BACKEND_URL=', BACKEND_URL);
