// Generate a runtime `frontend/config.js` file from environment variables.
// Usage: run during CI/build (Netlify) to write the BACKEND_URL that the frontend will use.
import fs from 'fs';
import path from 'path';

const RAW_BACKEND = process.env.BACKEND_URL || process.env.FRONTEND_BACKEND_URL || process.env.BACKEND_URLS || '';
// Support either a single BACKEND_URL or a comma-separated BACKEND_URLS list.
// Generator will write both `window.BACKEND_URLS` (array) and the legacy
// `window.BACKEND_URL` (first entry or empty string) for backwards compat.
const outDir = path.join(process.cwd(), 'frontend');
const outFile = path.join(outDir, 'config.js');

if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

const urls = RAW_BACKEND.split(',')
	.map(s => s.trim())
	.filter(Boolean);
const primary = urls.length ? urls[0] : '';

const content = `// Auto-generated by scripts/generate_frontend_config.js
// Set at build time by CI (Netlify) to point the frontend at one or more backends.
window.BACKEND_URLS = ${JSON.stringify(urls)};
// Backwards-compatible single value (first URL or empty):
window.BACKEND_URL = ${JSON.stringify(primary)};
`;

fs.writeFileSync(outFile, content, 'utf8');
console.log('Wrote', outFile, 'BACKEND_URLS=', urls, 'BACKEND_URL=', primary);
